citation-style-language/journals

- .gitignore
- README.mdown
- generate_styles.rb
> Complete migration

- agu/_journals.tab
- agu/_template.csl
- publishers.json
tables for AGU journals. 
Note: It is my first attempt to create this, so I hope there is not a lot of mistakes.
> AGU journals

- nrc/_journals.tab
- nrc/_template.csl
- publishers.json
> NRC journals

- informs/_README.mdown
- informs/_journals.tab
- informs/_skip.txt
- informs/_template.csl
- publishers.json
Accompanies https://github.com/citation-style-language/styles/pull/2354 and https://github.com/citation-style-language/styles/pull/2364.
> Add INFORMS metadata

- aip/_journals.tab
- aip/_template.csl
Add Journal of Vacuum Science & Technology parts A and B.
Replaces https://github.com/citation-style-language/styles/pull/2396 (pull request for independent style).
> Add AIP Journal of Vacuum Science & Technology styles

- taylor-and-francis/_extra.tab
- taylor-and-francis/_journals.tab
https://forums.zotero.org/discussion/comment/246647#Comment_246647
Not 100% sure about this as there is no other style in here that uses the T&F NLM style with numeric format.
> add Current Medical Research and Opinion

- acs/_journals.tab
Per https://forums.zotero.org/discussion/64081/style-problem-environmental-science-and-technology-letters
> Edit "Environmental Science &Technology Letters"

- taylor-and-francis/_extra.tab
Requested here: https://forums.zotero.org/discussion/49800/style-request-international-journal-of-radiation-biology
Sample paper here: http://www.tandfonline.com/doi/pdf/10.1080/09553002.2017.1231946
> add International Journal of Radiation Biology to taylor-and-francis

- README.mdown
- copernicus/_journals.tab
- generate_styles.rb
- healio/_journals.tab
- mdpi/_README.mdown
- mdpi/_journals.tab
- mdpi/_template.csl
(replaces https://github.com/citation-style-language/journals/pull/36)
> Update MDPI journal metadata

- rsc/_journals.tab
- rsc/_template.csl
In conjunction with: https://github.com/citation-style-language/styles/pull/2669
(the style there is on my patch branch 46, but the journals stuff is on patch branch 19. There is no way to combine these two in one PR, is there?)
> RSC journals: Edit template to allow selection of independent-parent

- acm/_README.mdown
- acm/_template.csl
to go with: https://github.com/citation-style-language/styles/pull/2633
> Update _template.csl of ACM

- rsc/_skip.txt
via https://forums.zotero.org/discussion/66697/style-change-request-chemistry-education-research-and-practice
Goes hand in hand with the new independent style: https://github.com/citation-style-language/styles/pull/2838
> Put chemistry-education-research-and-practice on RSC skip list

- amstat/_journals.tab
- amstat/_template.csl
- publishers.json
to go with the new Amstat style: https://github.com/citation-style-language/styles/pull/2842
> Create American Statistical Assocation folder etc.

- elsevier/_extra.tab
via https://forums.zotero.org/discussion/60282/style-request-arab-journal-of-urology
> Add Elsevier's Arab Journal of Urology to extra list

- elsevier/_skip.txt
Accompanies https://github.com/citation-style-language/styles/pull/2870
> Update Elsevier skip list

- ima/_journals.tab
- ima/_template.csl
- publishers.json
Replaces https://github.com/citation-style-language/journals/pull/51
> Add metadata for Institute of Mathematics and its Applications (IMA)

- elsevier-es/_journals.tab
- elsevier-es/_template.csl
- publishers.json
Per https://github.com/citation-style-language/styles/pull/2784
Accompanies https://github.com/citation-style-language/styles/pull/2901
> Add metadata for Spanish Elsevier journals

- integrated-science-publishing/_journals.tab
- integrated-science-publishing/_template.csl
- publishers.json
Accompanies https://github.com/citation-style-language/styles/pull/2992
> Add Integrated Science Publishing metadata

- acs/_README.mdown
- acs/_journals.tab
- acs/_template.csl
Per personal request by Jonathan Brill. See also https://github.com/citation-style-language/styles/pull/3009.
> Update ACS dependents

- elsevier/_extra.tab
- elsevier/_journals.tab
- elsevier/_skip.txt
Closes https://github.com/citation-style-language/styles/issues/3000
> Rename Elsevier's Natureza and Conservacao to Perspectives in Ecology and Conservation

- taylor-and-francis/_extra.tab
via https://github.com/citation-style-language/styles/issues/3039
> Add 'Materials Technology' to Taylor&Francis extra

- cell-press-research/_journals.tab
- cell-press-research/_template.csl
- elsevier/_skip.txt
Goes with https://github.com/citation-style-language/styles/pull/3064
Joule style was request via the website by a Cell editor.
> Update Cell Press Research metadata

- karger/_skip.txt
to go with: https://github.com/citation-style-language/styles/pull/3038
New independent style for Brain, Behavior and Evolution journal
> Create _skip.txt for Karger journals

- copernicus/_README.mdown
- copernicus/_journals.tab
via https://github.com/citation-style-language/styles/pull/3085#issuecomment-342738522
> Add Journal of Micropaleontology to Copernicus

- acs/_README.mdown
- acs/_journals.tab
- acs/_skip.txt
- acs/_template.csl
- nrc/_journals.tab
Requested by ACS.
See also https://twitter.com/acspublications/status/959090276047425536 for ACS announcement.
> ACS styles update

- springer/_extra.tab
- springer/_journals.tab
via https://forums.zotero.org/discussion/72036/csl-vancouver-bmc-bioinformatics-doi
(Let me know if you want this solved in a different way).
> Update _journals.tab (Springer BMC journals)

- taylor-and-francis/_extra.tab
Add metadata for "Archives and Manuscripts" journal to go with parent style: https://github.com/citation-style-language/styles/pull/3566
> Update _extra.tab (T&F)

- elsevier/_skip.txt
as per: https://github.com/citation-style-language/styles/pull/3654
> Update _skip.txt (international-biodeterioration-and-biodegradation)

- copernicus/_README.mdown
- copernicus/_journals.tab
- copernicus/_skip.txt
- copernicus/_template.csl
Accompanies https://github.com/citation-style-language/styles/pull/3679
> Update Copernicus journals metadata

- cell-press-research/_journals.tab
- elsevier/_skip.txt
See also https://github.com/citation-style-language/styles/pull/4327
> Update metadata of Cell Press journals

- mnhn/_journals.tab
- mnhn/_template.csl
- publishers.json
Per https://github.com/citation-style-language/styles/pull/4350, https://github.com/citation-style-language/journals/pull/83
> Add "Muséum national d'Histoire naturelle" journals

- aims/_journals.tab
- aims/_template.csl
- publishers.json
Replaces and closes https://github.com/citation-style-language/journals/pull/82
> Add "AIMS Press" journals

- aacr/_README.mdown
- aacr/_journals.tab
- aacr/_template.csl
See also https://github.com/citation-style-language/styles/pull/4492
> Update AACR metadata

- taylor-and-francis/_extra.tab
via https://forums.zotero.org/discussion/67179/style-request-terrorism-and-political-violence-journal
> add Terrorism and Political violence to T&F extras

- iop/_README.mdown
- iop/_journals.tab
- iop/_skip.txt
- iop/_template.csl
* Add new IOP journals
* Update dependents of The Astrophysical Journal (per https://github.com/citation-style-language/styles/pull/2698)
* Remove Journal of Instrumentation (per https://github.com/citation-style-language/styles/commit/2e2c9e6b96b3385c3465b1cee7e7de8968c0364f#diff-80c276da167ba6a599fea2d997ad81d9)
Closes https://github.com/citation-style-language/journals/pull/61
> Update IOP metadata

- npg/_journals.tab
- npg/_skip.txt
To go in hand with independent style: https://github.com/citation-style-language/styles/pull/4240
> Add Molecular Therapy to NPG Update _skip.txt

- begell-house/_journals.tab
- begell-house/_template.csl
- publishers.json
Per https://github.com/citation-style-language/styles/pull/4574 and https://github.com/citation-style-language/styles/pull/4575
> Add Begell House journals

- osa/_journals.tab
- osa/_template.csl
- publishers.json
Closes https://github.com/citation-style-language/journals/pull/93.
> Add The Optical Society (OSA) styles

- the-geological-society/_template.csl
> Update the-geological-society template

- generate_styles.rb
- pensoft/_journals.tab
- pensoft/_template.csl
- publishers.json
Closes https://github.com/citation-style-language/journals/pull/104
> Add Pensoft metadata

- springer/_extra.tab
Accompanies https://github.com/citation-style-language/styles/pull/4854
> Update metadata for GPS Solutions (Springer)

- taylor-and-francis/_extra.tab
via https://forums.zotero.org/discussion/85240/journal-formatting-idiosyncrasies#latest
> T&F: add Teaching and Learning in Medicine to _extra.tab

- npg/_journals.tab
https://forums.zotero.org/discussion/85139/style-request-translational-psychiatry#latest
> NPG: change parent style for Translational Psychiatry

- mnhn/_journals.tab
via https://github.com/citation-style-language/styles/pull/4350#issuecomment-641258319
> MNHN: add Comptes rendus Palevol

- springer/_skip.txt
in combination with indepedent style https://github.com/citation-style-language/styles/pull/4844
> Springer: remove new-zealand-journal-of-forestry-science

- acs/_journals.tab
- springer/_journals.tab
via https://forums.zotero.org/discussion/85135/change-in-jasms-citation-style#latest
> Springer>>ACS: Journal of The American Society for Mass Spectrometry

- cell-press-research/_journals.tab
- elsevier/_journals.tab
Companion to https://github.com/citation-style-language/styles/pull/5070
> Move Molecular Therapy Journals to Cell

- elsevier/_extra.tab
- elsevier/_journals.tab
- elsevier/_skip.txt
- springer/_extra.tab
Companion to https://github.com/citation-style-language/styles/pull/5072
> Switch Elsevier to its own Vancouver ad

- aosis/_journals.tab
- aosis/_template.csl
- elsevier/_skip.txt
- publishers.json
- springer/_skip.txt
closes https://github.com/citation-style-language/journals/issues/33
Attached the .xlsx in case you need to change anything: [aosis-journals.xlsx](https://github.com/citation-style-language/journals/files/6154779/aosis-journals.xlsx)
> Create AOSIS dependent styles

- aosis/_template.csl
via https://github.com/citation-style-language/journals/pull/116#issuecomment-802654688
> Update AOSIS _template.csl

- springer/_skip.txt
via https://github.com/citation-style-language/styles/issues/4816
in combination with independent style: https://github.com/citation-style-language/styles/pull/5534
> add estuaries-and-coasts to springer skip list

- taylor-and-francis/_extra.tab
via https://forums.zotero.org/discussion/88927/style-request-critical-reviews-in-toxicology#latest
> add several journals to T&F extra journals

- elsevier/_extra.tab
via https://forums.zotero.org/discussion/92904/style-request-combustion-and-flame#latest (25/11/2021)
and
via https://forums.zotero.org/discussion/94042/journal-not-in-the-style-repository#latest (21/01/2022)
> add 2 journals to Elsevier _extra.tab

- springer/_extra.tab
Just adding this as it was missing. Via https://forums.zotero.org/discussion/comment/385735/#Comment_385735
> add Journal of Plant Pathology to Springer extra.tab

- mal/_journals.tab
@POBrien333 there were a couple of issues with this, for future reference -- the diff isn't great, unfortunately, see if you can make sense of it
> Fix MAL journals.tab

- cell-press-research/_journals.tab
via https://github.com/citation-style-language/styles/pull/6023/files
> Update _journals.tab for cell-press-research

- elsevier/_skip.txt
to go with https://github.com/citation-style-language/styles/pull/6041
> Update _skip.txt (Elsevier)

- taylor-and-francis/_extra.tab
via https://forums.zotero.org/discussion/99198/style-request-topics-in-stroke-rehabilitation#latest
Requires https://github.com/citation-style-language/styles/pull/6221
--------------
via https://forums.zotero.org/discussion/95143/style-request-critical-reviews-in-food-science-and-nutrition#latest
Requires https://github.com/citation-style-language/styles/pull/6232
> Add Topics in Stroke Rehabilitation to T&F _extra.tab

- mp/_journals.tab
- mp/_template.csl
closes https://github.com/citation-style-language/journals/issues/125
> Create dependent Medicine Publishing styles

- publishers.json
> add "Medicine Publishing" to publishers.json

- springer/_skip.txt
via https://forums.zotero.org/discussion/94293/avian-research-citation-style-on-mendeley#latest
> add avian-research.csl to springer skip.txt list

- npg/_journals.tab
via https://forums.zotero.org/discussion/99392/zotero-style-for-nature-foods#latest
> add Nature Food

- springer/_extra.tab
via https://forums.zotero.org/discussion/96717/style-request-journal-of-plant-diseases-and-protection#latest
> add JPDP to Springer extra.tab

- elsevier/_extra.tab
https://forums.zotero.org/discussion/101577/style-request-resources-environment-and-sustainaility
> add Resources, Environment and Sustainaility to Elsevier extra.tab

- bup/_journals.tab
- bup/_template.csl
- publishers.json
via [#6356](https://github.com/citation-style-language/styles/pull/6356)
> create Bristol University Press dependent styles

- elsevier/_skip.txt
goes with https://github.com/citation-style-language/styles/pull/6567
> Update elsevier _skip.txt

- cell-press-research/_journals.tab
Some new journals, some clean-up of metadata
> Cell update

- elsevier/_extra.tab
- elsevier/_skip.txt
guidelines: https://www.sciencedirect.com/journal/journal-of-food-protection/publish/guide-for-authors
via https://forums.zotero.org/discussion/108961/style-error-journal-of-food-protection#latest
------
https://forums.zotero.org/discussion/112758/journal-pediatric-surgery-needs-updating#latest
https://github.com/citation-style-language/styles/pull/6968
> add JFP to Elsevier_extra.tab

- elsevier/_journals.tab
Goes with https://github.com/citation-style-language/styles/pull/7178
> Update _journals.tab (Journal of Veterinary Cardiology)

- springer/_journals.tab
https://forums.zotero.org/discussion/117495/how-can-i-change-reference-style-to-list-all-authors-and-not-et-al-as-a-requirement-of-the-the-journ#latest
> Switch parent style for Journal of Molecular Modeling (Springer)

- elsevier/_extra.tab
- elsevier/_journals.tab
https://forums.zotero.org/discussion/113753/vancouver-style#latest
> add The Journal of Climate Change and Health to Elsevier _extra.tab

- elsevier/_journals.tab
In additon to https://github.com/citation-style-language/styles/pull/7284
> Update Elsevier _journals.tab (Journal of Hepatology)

- springer/_extra.tab
Closes https://github.com/citation-style-language/styles/issues/6513
> Add "World Journal of Pediatrics" to Springer extra.tab
